# This file is used to configure the Travis CI tests for this repository

sudo: false


# It's necessary to do this just for codespell
language: python
python: 3.6


script:
  # Check for commonly misspelled words https://github.com/codespell-project/codespell
  - pip install codespell
  - codespell --skip="${TRAVIS_BUILD_DIR}/.git" "${TRAVIS_BUILD_DIR}"


notifications:
  email:
    on_success: always
    on_failure: always
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always
